name: Readme Change

on:
  repository_dispatch:
    types:
      - readme-changed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get changed README files
        run: |
          git fetch
          changed_files=$(git diff --name-only HEAD^)
          for changed_file in $changed_files
          do
            if [[ $changed_file =~ README.md ]]; then
              echo "Found changed README file: $changed_file"
            fi
          done
